[package]
name = "rust_sdl_gol"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.14.41", features = ["build-from-source", "ttf"] }
log = "0.4.27"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros", "time"] }
rayon = "1.11.0"
